const CONSTANTS = {
	AUDIO: {
		MEDIA_ERR_ABORTED: "MEDIA_ERR_ABORTED",							//获取资源被用户禁止
		MEDIA_ERR_NETWORD: "MEDIA_ERR_NETWORD",							//网络错误
		MEDIA_ERR_DECODE: "MEDIA_ERR_DECODE",							//解码错误
		MEDIA_ERR_SRC_NOT_SUPPOERTED: "MEDIA_ERR_SRC_NOT_SUPPOERTED"	//不合适资源
	}
}
module.exports = CONSTANTS;